#!/usr/bin/env python3
"""Print the JS prelude that figma/db_figma.js expects: THEMES, N, F, T and (optionally) SVG.

The values are read straight out of db_deck.py (parsed with `ast`, nothing imported, so no
python-pptx / cairosvg needed) — tokens and vectors keep ONE source of truth. Never copy them by hand.

  python3 scripts/figma_prelude.py --svg none                 # tokens only (~1.5 KB) — normal calls
  python3 scripts/figma_prelude.py --svg all --direction ecosystem   # first call on a page: installs the brand kit
  python3 scripts/figma_prelude.py --svg mark,eye              # explicit subset
"""
import argparse
import ast
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'db_deck.py')
WANT = ('THEMES', 'N', 'F', 'T', 'SVG')
# which vectors each direction's kit needs (the other direction's lockup is left out)
KIT = {
    'ecosystem':   ['mark', 'eye', 'wmTop', 'wmBottom', 'plate', 'quoteMark', 'ecoLockup'],
    'accelerator': ['mark', 'eye', 'wmTop', 'wmBottom', 'plate', 'quoteMark', 'accLockup'],
}


def load():
    tree = ast.parse(open(SRC, encoding='utf-8').read())
    out = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            if name in WANT:
                out[name] = ast.literal_eval(node.value)
    missing = [w for w in WANT if w not in out]
    if missing:
        sys.exit('db_deck.py no longer defines a literal: ' + ', '.join(missing))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--svg', default='none', help='none | all | comma-separated SVG keys')
    ap.add_argument('--direction', choices=sorted(KIT), help='with --svg all: only that direction\'s lockup')
    a = ap.parse_args()
    d = load()
    if a.svg == 'none':
        svg = {}
    elif a.svg == 'all':
        keys = KIT[a.direction] if a.direction else list(d['SVG'])
        svg = {k: d['SVG'][k] for k in keys}
    else:
        svg = {k: d['SVG'][k] for k in a.svg.split(',')}
    dump = lambda v: json.dumps(v, ensure_ascii=False, separators=(',', ':'))
    print('// prelude generated by scripts/figma_prelude.py from db_deck.py — do not edit')
    for k in ('THEMES', 'N', 'F', 'T'):
        print('const %s = %s;' % (k, dump(d[k])))
    print('const SVG = %s;' % dump(svg))


if __name__ == '__main__':
    main()
